### PR TITLE
Add support for OAuth2

### PR DESCRIPTION
**Pull request by danielfarrell**
Not sure if this was on your roadmap, but it is something we need for a project.  If you would like more added to it let me know.

### CODE REVIEW

**Comment by dlo** [comment]
This is great, thanks!

**Comment by gxela** [comment]
If everything works good we can tag the version 1.0.5 and add the changes to the changelog

**Comment by danielfarrell** [comment]
@gxela I'm using it here in a project and it is working well.

**Comment by memmott** [comment]
It worked well for me! Nice addition. The readme needs updating now though. See PR#19.

**Pull request merged**
