### PR TITLE
Add support for invoices

### LINKED ISSUE #15: Update to Python 3

### PR DESCRIPTION
**Pull request by benkonrath**

### CODE REVIEW

**Comment by kvarga** [comment]
Any thoughts on merging this @lionheart ?

**Comment by JaniKarh** [comment]
Any update on this?

**Comment by FlorianLudwig** [comment]
looks good to me. :+1:

**Comment by bennovack** [comment]
Trying to work with invoices right now, would love to get this merged in 👍

**Comment by benkonrath** [comment]
I just rebased this branch and removed the python 3 changes since it's already been fixed in master. It would be nice to still the support for invoices into the library. Thanks.

**Comment by dlo** [comment]
Thanks @benkonrath, this looks great, thanks so much for the contribution! 👍

**Pull request merged**
